from typing import Any


def hello_from_bin() -> str: ...
def parse_p21(input: str | bytes, strict: bool = True) -> dict[str, Any]: ...
def parse_sfc(input: str | bytes, strict: bool = True) -> dict[str, Any]: ...
