from os import PathLike
from typing import Any, Iterable, Literal, overload

def hello_from_bin() -> str: ...
def parse_p21(input: str | bytes, strict: bool = True) -> dict[str, Any]:
    """Read STEP records and common sheet/subfigure typed features and model."""
    ...
def parse_sfc(input: str | bytes, strict: bool = True) -> dict[str, Any]: ...
def serialize_p21(parsed: dict[str, Any]) -> bytes: ...
def write_p21(parsed: dict[str, Any], path: str | PathLike[str]) -> None: ...
def write_p21_bundle(source: str | PathLike[str], destination: str | PathLike[str], *, file_name: str | None = None) -> dict[str, Any]: ...
def write_p2z(source: str | PathLike[str], path: str | PathLike[str]) -> None: ...
def serialize_sfc(
    parsed: dict[str, Any], *, allow_external_references: bool = False,
    literal_backslashes: bool = False,
) -> bytes: ...
def write_sfc(
    parsed: dict[str, Any],
    path: str | PathLike[str],
    *,
    allow_external_references: bool = False,
    literal_backslashes: bool = False,
) -> None: ...
def write_sfc_bundle(
    source: str | PathLike[str],
    destination: str | PathLike[str],
    *,
    file_name: str | None = None,
    extra_files: list[str] | None = None,
) -> dict[str, Any]: ...
def new_sfc(
    file_name: str = "drawing.sfc",
    *,
    name: str = "drawing",
    paper: str | int | None = None,
    orientation: str | int | None = None,
    width_mm: int | float | None = None,
    height_mm: int | float | None = None,
    timestamp: str | None = None,
    target: Literal["sfc", "p21"] = "sfc",
) -> SfcDocument: ...
def edit_sfc(parsed: dict[str, Any]) -> SfcDocument: ...
def edit_sfc_bundle(source: str | PathLike[str]) -> SfcDocument: ...
def validate_saf(data: bytes) -> None: ...
def estimate_text_width(text: str, height: float = 3.5, spacing: float = 0.0) -> float:
    """Estimate horizontal monospaced width using CP932 cells and character gaps."""
    ...

class SfcDocument:
    @overload
    def extend(self, elements: Iterable[dict[str, Any]], *, on_invalid: Literal["raise"] = "raise", into: int | None = None) -> list[int | list[int]]: ...
    @overload
    def extend(self, elements: Iterable[dict[str, Any]], *, on_invalid: Literal["skip"], into: int | None = None) -> tuple[list[int | list[int] | None], list[tuple[int, str]]]: ...
    def create_part(self, name: str, entity_ids: list[int], placements: Iterable[dict[str, Any]]) -> list[int]:
        """Create a shared part with only explicitly supplied placements."""
        ...
    @overload
    def to_p21_bytes(self, *, unsupported: Literal["raise", "drop"] = "raise", report: Literal[False] = False) -> bytes: ...
    @overload
    def to_p21_bytes(self, *, unsupported: Literal["raise", "drop"] = "raise", report: Literal[True]) -> tuple[bytes, list[tuple[int, str]]]: ...
    def validate_p21(self) -> list[tuple[int, str]]: ...
    def save_p21(self, path: str | PathLike[str]) -> None: ...
    def save_p21_bundle(self, destination: str | PathLike[str], *, file_name: str | None = None) -> dict[str, Any]: ...
    def to_p2z_bytes(self, *, file_name: str | None = None) -> bytes: ...
    def save_p2z(self, path: str | PathLike[str]) -> None: ...
    def save_bundle(self, destination: str | PathLike[str], *, file_name: str | None = None, literal_backslashes: bool = False) -> dict[str, Any]: ...
    def saf_bytes(self) -> bytes | None: ...
    def set_attribute(self, entity_id: int, name: str, value: str, *, attribute_type: str = "STR", unit: str | None = None, group: list[str] | None = None, set_name: str = "ezsxf attributes", set_version: str = "1.0", designed_by: str = "ezsxf", figure_name: str = "figure") -> str: ...
    def get_attributes(self, entity_id: int) -> list[dict[str, Any]]: ...
    def remove_attribute(self, entity_id: int, name: str, *, group: list[str] | None = None, set_name: str = "ezsxf attributes", set_version: str = "1.0", designed_by: str = "ezsxf") -> None: ...
    def remove_attachment(self, entity_id: int) -> None: ...
    def set_single_attribute(self, entity_id: int, figure_name: str, name: str, value: str, *, attribute_type: str = "STR", unit: str | None = None) -> str: ...
    def set_text_attribute(self, entity_id: int, name: str, *, attribute_type: str | None = None, unit: str | None = None) -> str: ...
    def add_dependency(self, source: str | PathLike[str], *, file_name: str | None = None) -> str: ...
    def add_image(self, image: str | PathLike[str], anchor: tuple[float, float], width_mm: float, height_mm: float, *, angle: float = 0.0, layer: int = 1, file_name: str | None = None) -> int: ...
    def update_image(self, entity_id: int, anchor: tuple[float, float], width_mm: float, height_mm: float, *, angle: float = 0.0, image: str | PathLike[str] | None = None, file_name: str | None = None) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_bytes(self, *, allow_external_references: bool = False, literal_backslashes: bool = False) -> bytes: ...
    def save(
        self, path: str | PathLike[str], *, allow_external_references: bool = False,
        literal_backslashes: bool = False,
    ) -> None: ...
    def add_layer(self, name: str, *, visible: bool = True) -> int: ...
    def rename_layer(self, code: int, name: str) -> None: ...
    def add_font(self, name: str) -> int:
        """Return the existing exact-name font code, or append a new font."""
        ...
    def add_color(self, color: str | tuple[int, int, int] | list[int]) -> int:
        """Return the code of a predefined name or an exact RGB definition."""
        ...
    def add_line_type(self, name: str, *, pattern: list[float] | tuple[float, ...] | None = None) -> int:
        """Use a predefined name, or 2/4/6/8 positive draw/gap lengths in mm."""
        ...
    def add_line_width(self, width_mm: float) -> int:
        """Reuse an exact width or create a paper-mm width definition."""
        ...
    def add_line(
        self,
        start: tuple[float, float],
        end: tuple[float, float],
        *,
        layer: int = 1,
        color: int = 1,
        line_type: int = 1,
        line_width: int = 1,
    ) -> int: ...
    def add_circle(
        self,
        center: tuple[float, float],
        radius: float,
        *,
        layer: int = 1,
        color: int = 1,
        line_type: int = 1,
        line_width: int = 1,
    ) -> int: ...
    def add_arc(
        self,
        center: tuple[float, float],
        radius: float,
        start_angle: float,
        end_angle: float,
        *,
        direction: int = 0,
        layer: int = 1,
        color: int = 1,
        line_type: int = 1,
        line_width: int = 1,
    ) -> int: ...
    def add_polyline(
        self,
        points: list[tuple[float, float]],
        *,
        layer: int = 1,
        color: int = 1,
        line_type: int = 1,
        line_width: int = 1,
    ) -> int: ...
    def add_text(
        self,
        text: str,
        anchor: tuple[float, float],
        *,
        height: float = 3.5,
        width: float | None = None,
        spacing: float = 0.0,
        angle: float = 0.0,
        slant: float = 0.0,
        base_point: int = 1,
        direction: int = 1,
        layer: int = 1,
        color: int = 1,
        font: int = 1,
    ) -> int: ...
    def update_element(self, entity_id: int, **changes: Any) -> None: ...
    def remove_element(self, entity_id: int) -> None: ...
    def add_feature(self, kind: str, **fields: Any) -> int: ...
    def group_elements(self, name: str, entity_ids: list[int], *, kind: int = 3, position: tuple[float, float] = (0.0, 0.0), angle: float = 0.0, scale: tuple[float, float] = (1.0, 1.0), layer: int = 0) -> int: ...
    def ungroup(self, placement_id: int) -> None: ...
    def add_to_group(self, placement_id: int, entity_ids: list[int]) -> None: ...
    def place_part(self, placement_id: int, *, position: tuple[float, float] = (0.0, 0.0), angle: float = 0.0, scale: tuple[float, float] = (1.0, 1.0), layer: int = 1) -> int: ...
    def rename_group(self, placement_id: int, name: str) -> None: ...
    def add_composite_curve(self, entity_ids: list[int], *, visible: bool = False, color: int = 1, line_type: int = 1, line_width: int = 1) -> int: ...
    def add_fill(self, outer: int, *, holes: list[int] | None = None, layer: int = 1, color: int = 1) -> int: ...
    def add_hatch(self, outer: int, patterns: list[list[int | float]], *, holes: list[int] | None = None, layer: int = 1) -> int: ...
    def update_hatch_boundaries(self, entity_id: int, outer: int, *, holes: list[int] | None = None) -> None: ...
    def release_composite_curve(self, entity_id: int) -> None: ...
    def update_hatch_patterns(self, entity_id: int, patterns: list[list[int | float]]) -> None: ...
